// Generated by scripts/gen-opengrants.mjs from openapi.json. Do not edit by hand.
// OpenGrants API 1.2.0

export const OPENGRANTS_BASE_URL = "https://ops.opengrants.io/functions/v1";

export interface OpenGrantsHttp {
  request(method: string, path: string, query: Record<string, string | number | boolean | undefined>, body?: unknown): Promise<unknown>;
}

/** GET /grants-api — List grants */
export interface ListGrantsQuery {
  search?: string;
  /** Ranking strategy. semantic/hybrid require a search term and enable vector relevance. */
  search_mode?: "keyword" | "semantic" | "hybrid";
  status?: "open" | "posted" | "closed" | "forecasted";
  /** 'open' (default) returns applyable opportunities only. 'awarded' returns previously funded projects (research mode — not open for application; deadline is null, see project_end_date). 'all' returns both. */
  opportunity_type?: "open" | "awarded" | "all";
  category?: string;
  /** Filter by US location: comma-separated 2-letter USPS codes, e.g. CA,NY. State-specific only unless include_national=true. */
  states?: string;
  /** When filtering by states, also include national / all-states opportunities. */
  include_national?: boolean;
  /** Legacy free-text location filter (best-effort, state-canonicalized on hybrid). Prefer 'states'. @deprecated */
  geography?: string;
  min_amount?: number;
  max_amount?: number;
  deadline_after?: string;
  deadline_before?: string;
  posted_after?: string;
  sort_by?: "created_at" | "deadline_date" | "amount_min" | "amount_max" | "title";
  order?: "asc" | "desc";
  /** Return only { total } for the filter set. */
  count_only?: boolean;
  include_archived?: boolean;
  limit?: number;
  offset?: number;
}
export type ListGrantsResponse = unknown;
export function listGrants(http: OpenGrantsHttp, query: ListGrantsQuery = {}): Promise<ListGrantsResponse> {
  return http.request("GET", `/grants-api`, query as Record<string, string | number | boolean | undefined>) as Promise<ListGrantsResponse>;
}

/** GET /contracts-api — List contracts */
export interface ListContractsQuery {
  search?: string;
  /** Ranking strategy. semantic/hybrid require a search term and enable vector relevance. */
  search_mode?: "keyword" | "semantic" | "hybrid";
  status?: string;
  /** 'open' (default) returns active solicitations only. 'awarded' returns already-awarded contracts (research mode). 'all' returns both. */
  opportunity_type?: "open" | "awarded" | "all";
  category?: string;
  naics?: string;
  set_aside?: string;
  /** Filter by US location: comma-separated 2-letter USPS codes, e.g. CA,NY. State-specific only unless include_national=true. */
  states?: string;
  /** When filtering by states, also include national / all-states opportunities. */
  include_national?: boolean;
  /** Legacy free-text location filter (best-effort, state-canonicalized on hybrid). Prefer 'states'. @deprecated */
  geography?: string;
  min_amount?: number;
  max_amount?: number;
  deadline_after?: string;
  deadline_before?: string;
  posted_after?: string;
  sort_by?: "created_at" | "deadline_date" | "amount_min" | "amount_max" | "title";
  order?: "asc" | "desc";
  /** Return only { total } for the filter set. */
  count_only?: boolean;
  include_archived?: boolean;
  limit?: number;
  offset?: number;
}
export type ListContractsResponse = unknown;
export function listContracts(http: OpenGrantsHttp, query: ListContractsQuery = {}): Promise<ListContractsResponse> {
  return http.request("GET", `/contracts-api`, query as Record<string, string | number | boolean | undefined>) as Promise<ListContractsResponse>;
}

/** GET /funders-api — List funders */
export interface ListFundersQuery {
  search?: string;
  limit?: number;
  offset?: number;
}
export type ListFundersResponse = unknown;
export function listFunders(http: OpenGrantsHttp, query: ListFundersQuery = {}): Promise<ListFundersResponse> {
  return http.request("GET", `/funders-api`, query as Record<string, string | number | boolean | undefined>) as Promise<ListFundersResponse>;
}

/** GET /grants-api/{id} — Get a grant by ID */
export type GetGrantResponse = unknown;
export function getGrant(http: OpenGrantsHttp, id: string): Promise<GetGrantResponse> {
  return http.request("GET", `/grants-api/${encodeURIComponent(id)}`, {}) as Promise<GetGrantResponse>;
}

/** GET /contracts-api/{id} — Get a contract by ID */
export type GetContractResponse = unknown;
export function getContract(http: OpenGrantsHttp, id: string): Promise<GetContractResponse> {
  return http.request("GET", `/contracts-api/${encodeURIComponent(id)}`, {}) as Promise<GetContractResponse>;
}

/** GET /funders-api/{id} — Get a funder by ID */
export type GetFunderResponse = unknown;
export function getFunder(http: OpenGrantsHttp, id: string): Promise<GetFunderResponse> {
  return http.request("GET", `/funders-api/${encodeURIComponent(id)}`, {}) as Promise<GetFunderResponse>;
}

/** POST /match-grants-api — Match grants to an organization profile */
export type MatchGrantsBody = {
  profile: {
    /** Required. What your organization does. */
    mission: string;
    sector?: string;
    /** Applicant location; canonicalized to US states / national. */
    geography?: string;
    applicant_type?: "nonprofit" | "for_profit" | "municipality" | "tribal" | "individual" | "academic";
    is_501c3?: boolean;
    annual_budget_usd?: number;
    /** Accepted for profile parity; not used for grant scoring. */
    naics_code?: string;
    /** Accepted for profile parity; not used for grant scoring. */
    certifications?: string[];
    year_founded?: number;
  };
  /** Optional keywords to boost topical matches. */
  focus_keywords?: string[];
  limit?: number;
};
export type MatchGrantsResponse = {
  count?: number;
  matches?: ({
    id?: string;
    title?: string;
    funder?: string | null;
    match_score?: number;
    why_it_fits?: string;
    award_min_usd?: number | null;
    award_max_usd?: number | null;
    deadline?: string | null;
    url?: string | null;
  })[];
};
export function matchGrants(http: OpenGrantsHttp, body: MatchGrantsBody): Promise<MatchGrantsResponse> {
  return http.request("POST", `/match-grants-api`, {}, body) as Promise<MatchGrantsResponse>;
}
