/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as DevKitchenSinkRouteImport } from './routes/[_]dev/kitchen-sink'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalSecurityRouteImport } from './routes/portal/security'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceSecurityRouteImport } from './routes/workspace/security'
import { Route as WorkspaceSettingsBrandRouteImport } from './routes/workspace/settings/brand'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const DevKitchenSinkRoute = DevKitchenSinkRouteImport.update({
  id: '/_dev/kitchen-sink',
  path: '/_dev/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalSecurityRoute = PortalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PortalRouteRoute,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSecurityRoute = WorkspaceSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsBrandRoute = WorkspaceSettingsBrandRouteImport.update({
  id: '/settings/brand',
  path: '/settings/brand',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/_dev/kitchen-sink': typeof DevKitchenSinkRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/portal/security': typeof PortalSecurityRoute
  '/workspace/security': typeof WorkspaceSecurityRoute
  '/portal/': typeof PortalIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/settings/brand': typeof WorkspaceSettingsBrandRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/_dev/kitchen-sink': typeof DevKitchenSinkRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/portal/security': typeof PortalSecurityRoute
  '/workspace/security': typeof WorkspaceSecurityRoute
  '/portal': typeof PortalIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/settings/brand': typeof WorkspaceSettingsBrandRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/_dev/kitchen-sink': typeof DevKitchenSinkRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/portal/security': typeof PortalSecurityRoute
  '/workspace/security': typeof WorkspaceSecurityRoute
  '/portal/': typeof PortalIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/settings/brand': typeof WorkspaceSettingsBrandRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/workspace'
    | '/setup'
    | '/signin'
    | '/_dev/kitchen-sink'
    | '/auth/verify'
    | '/portal/security'
    | '/workspace/security'
    | '/portal/'
    | '/workspace/'
    | '/workspace/settings/brand'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/signin'
    | '/_dev/kitchen-sink'
    | '/auth/verify'
    | '/portal/security'
    | '/workspace/security'
    | '/portal'
    | '/workspace'
    | '/workspace/settings/brand'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/workspace'
    | '/setup'
    | '/signin'
    | '/_dev/kitchen-sink'
    | '/auth/verify'
    | '/portal/security'
    | '/workspace/security'
    | '/portal/'
    | '/workspace/'
    | '/workspace/settings/brand'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
  SigninRoute: typeof SigninRoute
  DevKitchenSinkRoute: typeof DevKitchenSinkRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/kitchen-sink': {
      id: '/_dev/kitchen-sink'
      path: '/_dev/kitchen-sink'
      fullPath: '/_dev/kitchen-sink'
      preLoaderRoute: typeof DevKitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/security': {
      id: '/portal/security'
      path: '/security'
      fullPath: '/portal/security'
      preLoaderRoute: typeof PortalSecurityRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/security': {
      id: '/workspace/security'
      path: '/security'
      fullPath: '/workspace/security'
      preLoaderRoute: typeof WorkspaceSecurityRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/settings/brand': {
      id: '/workspace/settings/brand'
      path: '/settings/brand'
      fullPath: '/workspace/settings/brand'
      preLoaderRoute: typeof WorkspaceSettingsBrandRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface PortalRouteRouteChildren {
  PortalSecurityRoute: typeof PortalSecurityRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalSecurityRoute: PortalSecurityRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface WorkspaceRouteRouteChildren {
  WorkspaceSecurityRoute: typeof WorkspaceSecurityRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceSettingsBrandRoute: typeof WorkspaceSettingsBrandRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceSecurityRoute: WorkspaceSecurityRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceSettingsBrandRoute: WorkspaceSettingsBrandRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  SetupRoute: SetupRoute,
  SigninRoute: SigninRoute,
  DevKitchenSinkRoute: DevKitchenSinkRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
